### PR TITLE
Add docs and support "new CRC" format in addition to "new ascii" format currently used

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by dralley** [comment]
I'd like to add some nicer abstractions, maybe something along the lines of 


```rust
let writer = cpio::ArchiveWriter::new(Cursor::new(Vec::new()));   // or ::new_with_checksum()

writer.add_file("./path/to/file")?;
writer.add_directory("./path/to/dir")?;

let buf = writer.finish()?;

let reader = cpio::ArchiveReader::new(buf);

for entry in reader {
    let entry = entry?;
    println!("{}", entry.ino());
    entry.read()?;   // will probably need to play around with this bit to make the lifetimes workable but we'll see
}

```

Are you amenable to this?

**Review by jcreekmore — CHANGES_REQUESTED** [review]
Can you add a test to show that writing out a checksum ensures that the read file is a Crc file and has the set checksum on it. Then, modify the existing single file test to show that the checksum returned is None and that the file type is Newc. Finally, it would also be nice to extend the multi file test to show that you can have both types of entries in one CPIO archive.

**Comment by jcreekmore** [comment]
> I'd like to add some nicer abstractions, maybe something along the lines of 
> 
> 
> 
> 
> 
> ```rust
> 
> let writer = cpio::ArchiveWriter::new(Cursor::new(Vec::new()));   // or ::new_with_checksum()
> 
> 
> 
> writer.add_file("./path/to/file")?;
> 
> writer.add_directory("./path/to/dir")?;
> 
> 
> 
> let buf = writer.finish()?;
> 
> 
> 
> let reader = cpio::ArchiveReader::new(buf);
> 
> 
> 
> for entry in reader {
> 
>     let entry = entry?;
> 
>     println!("{}", entry.ino());
> 
>     entry.read()?;   // will probably need to play around with this bit to make the lifetimes workable but we'll see
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> Are you amenable to this?

I have no issues with taking a PR for some nice abstractions. I would just request that whatever you do still allows for the contents of each file to not have to be read or written in one go in a single buffer (I don't mind a helper read or a write like you have that gives you the option, but I don't want to require the user to hold the entire entry contents in memory).

**Comment by dralley** [comment]
>Finally, it would also be nice to extend the multi file test to show that you can have both types of entries in one CPIO archive.

Is that something which happens "in the wild" so to speak?  There's nothing structurally wrong with supporting it, but it's a bit weird to test if it's not considered a normal behavior.

**Comment by jcreekmore** [comment]
Honestly? I have no idea. The format just seems to support it. I don't see any reason why someone couldn't append an entry encoded with the different format to the end of an existing CPIO archive and the utility should be able to handle it.

**Comment by jcreekmore** [comment]
I rebased and fixed this up in #17

**Pull request closed without merging**
